import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from skimage import color, io, transform as sk_transform
from PIL import Image
import argparse

import torch
import torch.nn as nn
import torch.nn.functional as F

# Define Hyperparameters
IMAGE_SIZE = 128
NUM_BINS = 313

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Cell 2: Gamut Definition and Rebalancing Weights
def build_synthetic_gamut():
    """
    Constructs a synthetic representation of the 313 CIE ab color gamut bins
    and uniform prior probabilities for class rebalancing.
    """
    # Create a grid ranging from -110 to 110 with a step of 10
    a_range = np.arange(-110, 120, 10)
    b_range = np.arange(-110, 120, 10)
    aa, bb = np.meshgrid(a_range, b_range)

    # Filter grid to simulate a circular gamut typical of Lab space
    distances = np.sqrt(aa**2 + bb**2)
    valid_mask = distances <= 110
    a_valid = aa[valid_mask]
    b_valid = bb[valid_mask]

    # STRICT FIX: Ensure exactly NUM_BINS are generated by slicing the result
    # This prevents the index out of bounds error in the dataset __getitem__
    q_ab = np.vstack((a_valid, b_valid)).T
    if len(q_ab) > NUM_BINS:
        q_ab = q_ab[:NUM_BINS]
    elif len(q_ab) < NUM_BINS:
        pad_len = NUM_BINS - len(q_ab)
        q_ab = np.pad(q_ab, ((0, pad_len), (0, 0)), 'edge')

    # Simulate prior probabilities (normally computed empirically over a dataset)
    prior_probs = np.random.uniform(0.01, 1.0, size=(NUM_BINS,))
    prior_probs /= np.sum(prior_probs)
    return q_ab, prior_probs

# Cell 4: U-Net Architecture with Global Context and MC Dropout
class ConvBlock(nn.Module):
    """ Standard Double Convolution Block with Batch Normalization """
    def __init__(self, in_channels, out_channels):
        super(ConvBlock, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.conv(x)

class GlobalContextModule(nn.Module):
    """
    Extracts global semantic priors from the lowest resolution feature map.
    Compresses spatial dimensions via Adaptive Average Pooling.
    """
    def __init__(self, in_channels, out_channels=256):
        super(GlobalContextModule, self).__init__()
        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Sequential(
            nn.Linear(in_channels, out_channels),
            nn.ReLU(inplace=True),
            nn.Linear(out_channels, out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        x = self.global_pool(x).view(x.size(0), -1)
        x = self.fc(x)
        return x # Shape: (B, 256)

class ColorizationUNet(nn.Module):
    def __init__(self, num_bins=313):
        super(ColorizationUNet, self).__init__()

        # Encoder Pathway
        self.enc1 = ConvBlock(1, 64)
        self.pool1 = nn.MaxPool2d(2)
        self.enc2 = ConvBlock(64, 128)
        self.pool2 = nn.MaxPool2d(2)
        self.enc3 = ConvBlock(128, 256)
        self.pool3 = nn.MaxPool2d(2)

        # Bottleneck Layer
        self.bottleneck = ConvBlock(256, 512)

        # Epistemic Uncertainty Enabler: Dropout injected at the bottleneck
        self.dropout = nn.Dropout2d(p=0.5)

        # Global Feature Pathway branching from the abstract Bottleneck
        self.global_module = GlobalContextModule(512, 256)

        # Fusion Layer mapping concatenated (Global + Bottleneck) features
        self.fusion = nn.Sequential(
            nn.Conv2d(512 + 256, 512, kernel_size=1),
            nn.ReLU(inplace=True)
        )

        # Decoder Pathway
        self.up1 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.dec1 = ConvBlock(512 + 256, 256)

        self.up2 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.dec2 = ConvBlock(256 + 128, 128)

        self.up3 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.dec3 = ConvBlock(128 + 64, 64)

        # Final Convolution projecting directly to the quantized 313 color bins
        self.final_conv = nn.Conv2d(64, num_bins, kernel_size=1)

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool1(e1))
        e3 = self.enc3(self.pool2(e2))

        b = self.bottleneck(self.pool3(e3))
        b = self.dropout(b)

        g_feat = self.global_module(b)
        b_h, b_w = b.size()[2:]
        g_expanded = g_feat.unsqueeze(-1).unsqueeze(-1).expand(-1, -1, b_h, b_w)

        fused = torch.cat([b, g_expanded], dim=1)
        fused = self.fusion(fused)

        d1 = self.up1(fused)
        d1 = torch.cat([d1, e3], dim=1)
        d1 = self.dropout(self.dec1(d1))

        d2 = self.up2(d1)
        d2 = torch.cat([d2, e2], dim=1)
        d2 = self.dec2(d2)

        d3 = self.up3(d2)
        d3 = torch.cat([d3, e1], dim=1)
        d3 = self.dec3(d3)

        out_logits = self.final_conv(d3)
        return out_logits

# Cell 5: Decoders
def argmax_decode(logits, q_ab):
    """
    Argmax decoding: selects the single most confident color bin per pixel.
    Produces more saturated and vibrant colors (better for GAN training).
    RECOMMENDED: Use this for colorization with GAN.
    """
    bin_indices = torch.argmax(logits, dim=1)  # Shape: (B, H, W)
    q_tensor = torch.tensor(q_ab, dtype=torch.float32, device=logits.device)
    ab_pred = q_tensor[bin_indices.cpu().numpy()]  # Shape: (B, H, W, 2)
    ab_pred = ab_pred.permute(0, 3, 1, 2)  # Shape: (B, 2, H, W)
    return ab_pred

def annealed_mean_decode(logits, q_ab, T=0.38):
    """
    Soft-decoding: averages across bins weighted by softmax probabilities.
    Produces smooth but potentially desaturated colors.
    """
    logits_scaled = logits / T
    probs = F.softmax(logits_scaled, dim=1)

    q_tensor = torch.FloatTensor(q_ab).to(logits.device)
    q_tensor = q_tensor.transpose(0, 1)
    q_tensor = q_tensor.unsqueeze(0).unsqueeze(-1).unsqueeze(-1)

    probs_expanded = probs.unsqueeze(1)
    ab_pred = torch.sum(probs_expanded * q_tensor, dim=2)
    return ab_pred

def preprocess_image(image_path, image_size=128):
    """
    Load and preprocess an image for colorization.
    Converts RGB to Lab and extracts the L channel.
    """
    # Load image
    img = io.imread(image_path)

    # Convert to RGB if grayscale
    if len(img.shape) == 2:
        img = color.gray2rgb(img)
    elif img.shape[2] == 4:  # RGBA
        img = img[:, :, :3]

    # Resize to target size
    img_resized = sk_transform.resize(img, (image_size, image_size), mode='reflect', anti_aliasing=True)

    # Convert to Lab color space
    lab_img = color.rgb2lab(img_resized)

    # Extract and normalize the Luminance (L) channel to [-1, 1]
    l_chan = lab_img[:, :, 0]
    l_chan = (l_chan / 50.0) - 1.0
    l_tensor = torch.FloatTensor(l_chan).unsqueeze(0).unsqueeze(0)  # Shape: (1, 1, H, W)

    return l_tensor.to(device), lab_img

def postprocess_image(l_original, ab_pred, original_size):
    """
    Convert predicted ab channels back to RGB image.
    """
    # Convert tensors to numpy
    l_np = l_original.squeeze().cpu().numpy()
    ab_pred_np = ab_pred.squeeze().permute(1, 2, 0).cpu().numpy()

    # Denormalize L channel back to [0, 100]
    l_np = (l_np + 1.0) * 50.0

    # Resize ab channels to original size if needed
    if ab_pred_np.shape[:2] != original_size:
        ab_pred_np = sk_transform.resize(ab_pred_np, original_size, mode='reflect', anti_aliasing=True)

    # Combine L and ab channels
    lab_pred = np.stack([l_np, ab_pred_np[:, :, 0], ab_pred_np[:, :, 1]], axis=2)

    # Convert Lab to RGB
    rgb_pred = color.lab2rgb(lab_pred)

    # Clip to valid range
    rgb_pred = np.clip(rgb_pred, 0, 1)

    return rgb_pred

def create_grayscale_image(l_original, original_size):
    """
    Create a grayscale version of the original image for comparison.
    """
    l_np = l_original.squeeze().cpu().numpy()
    l_np = (l_np + 1.0) * 50.0

    # Create grayscale RGB image
    gray_rgb = np.stack([l_np, l_np, l_np], axis=2) / 100.0
    gray_rgb = np.clip(gray_rgb, 0, 1)

    return gray_rgb

def run_inference(model_path, image_paths, output_dir="results", use_argmax=True):
    """
    Run colorization inference on a list of images.
    """
    # Build synthetic gamut
    q_ab, _ = build_synthetic_gamut()

    # Load model
    model = ColorizationUNet(num_bins=NUM_BINS).to(device)
    checkpoint = torch.load(model_path, map_location=device)
    model.load_state_dict(checkpoint['model_state_dict'] if 'model_state_dict' in checkpoint else checkpoint)
    model.eval()

    print(f"Loaded model from {model_path}")
    print(f"Running inference on {device}")

    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    for image_path in image_paths:
        print(f"Processing: {image_path}")

        # Preprocess image
        l_input, lab_original = preprocess_image(image_path, IMAGE_SIZE)
        original_size = lab_original.shape[:2]

        with torch.no_grad():
            # Run model
            logits = model(l_input)

            # Decode predictions
            if use_argmax:
                ab_pred = argmax_decode(logits, q_ab)
            else:
                # Use annealed mean decode for smoother results
                ab_pred = annealed_mean_decode(logits, q_ab, T=0.38)

        # Postprocess to get colorized image
        colorized_rgb = postprocess_image(l_input, ab_pred, original_size)

        # Create grayscale version for comparison
        grayscale_rgb = create_grayscale_image(l_input, original_size)

        # Save results
        base_name = os.path.splitext(os.path.basename(image_path))[0]

        # Save colorized image
        colorized_pil = Image.fromarray((colorized_rgb * 255).astype(np.uint8))
        colorized_pil.save(os.path.join(output_dir, f"{base_name}_colorized.png"))

        # Save grayscale image
        grayscale_pil = Image.fromarray((grayscale_rgb * 255).astype(np.uint8))
        grayscale_pil.save(os.path.join(output_dir, f"{base_name}_grayscale.png"))

        # Create comparison plot
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))

        # Original grayscale
        axes[0].imshow(grayscale_rgb)
        axes[0].set_title('Input (Grayscale)')
        axes[0].axis('off')

        # Colorized result
        axes[1].imshow(colorized_rgb)
        axes[1].set_title('Colorized Output')
        axes[1].axis('off')

        # Load original if available for comparison
        try:
            original_img = io.imread(image_path)
            if len(original_img.shape) == 2:
                original_img = color.gray2rgb(original_img)
            elif original_img.shape[2] == 4:
                original_img = original_img[:, :, :3]
            original_img = sk_transform.resize(original_img, original_size, mode='reflect', anti_aliasing=True)

            axes[2].imshow(original_img)
            axes[2].set_title('Ground Truth (if available)')
            axes[2].axis('off')
        except:
            axes[2].axis('off')

        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, f"{base_name}_comparison.png"), dpi=150, bbox_inches='tight')
        plt.close()

        print(f"Saved results to {output_dir}")

def main():
    parser = argparse.ArgumentParser(description='Colorize grayscale images using trained model')
    parser.add_argument('--model', type=str, required=True, help='Path to trained model checkpoint')
    parser.add_argument('--images', nargs='+', required=True, help='Paths to input images')
    parser.add_argument('--output', type=str, default='results', help='Output directory for results')
    parser.add_argument('--decode', choices=['argmax', 'annealed'], default='argmax',
                       help='Decoding method: argmax (vibrant) or annealed (smooth)')

    args = parser.parse_args()

    use_argmax = args.decode == 'argmax'
    run_inference(args.model, args.images, args.output, use_argmax)

if __name__ == "__main__":
    main()